# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.runs/synth_1/base_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.cache/wt [current_project]
set_property parent.project_path C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/ip_repo/notgate_1.0
  c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/ip_repo/camera_decode_1.0
  c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/ip_repo/sad_1.0
  c:/Users/cl/Desktop/OV7670_PYNQ/boards/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/hdl/base_wrapper.v
add_files C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/base.bd
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_0/base_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_1/base_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_protocol_convert_0_0/base_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_0/base_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_0/base_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_0/base_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_0/base_iic_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_0/base_iic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_1/base_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_1/base_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_1/base_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_1/base_intr_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_1/base_intr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_1/base_intr_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_dlmb_v10_1/base_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ilmb_v10_1/base_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_1/base_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_1/base_lmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_1/base_mb_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_1/base_mb_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_1/base_mb_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_1/base_mb_bram_ctrl_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_3/base_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0/base_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0/base_spi_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0/base_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0/base_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_1/base_gpio_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_1/base_gpio_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_gpio_1/base_gpio_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_1/base_iic_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_1/base_iic_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_2/base_intc_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_2/base_intc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_2/base_intc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_2/base_intr_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_2/base_intr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_2/base_intr_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_dlmb_v10_2/base_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ilmb_v10_2/base_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_2/base_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_2/base_lmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_2/base_mb_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_2/base_mb_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_2/base_mb_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_4/base_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1/base_spi_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1/base_spi_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1/base_spi_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1/base_spi_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_7/base_timer_7.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_7/base_timer_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_0_0/base_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_0_0/base_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_1_0/base_iic_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_iic_1_0/base_iic_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_3/base_intc_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_3/base_intc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intc_3/base_intc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_3/base_intr_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_3/base_intr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_intr_3/base_intr_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_dlmb_v10_3/base_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ilmb_v10_3/base_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_3/base_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_lmb_bram_if_cntlr_3/base_lmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_3/base_mb_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_3/base_mb_3_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_3/base_mb_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_3/base_mb_bram_ctrl_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_5/base_xbar_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rpi_gpio_0/base_rpi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rpi_gpio_0/base_rpi_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rpi_gpio_0/base_rpi_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_3/base_rst_clk_wiz_1_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_3/base_rst_clk_wiz_1_100M_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_clk_wiz_1_100M_3/base_rst_clk_wiz_1_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0_0/base_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0_0/base_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0_0/base_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_0_0/base_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1_0/base_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1_0/base_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1_0/base_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_spi_1_0/base_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_0_1/base_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_0_1/base_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_1/base_timer_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_1/base_timer_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_uartlite_1/base_uartlite_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_uartlite_1/base_uartlite_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_uartlite_1/base_uartlite_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_leds_gpio_0/base_leds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mdm_1_0/base_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mdm_1_0/base_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_6/base_xbar_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_7/base_xbar_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_xbar_8/base_xbar_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_switches_gpio_0/base_switches_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_system_interrupts_0/base_system_interrupts_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axis_data_fifo_0_0/base_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_trace_cntrl_64_0_0/constraints/trace_cntrl_64_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axis_data_fifo_0_1/base_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_trace_cntrl_32_0_0/constraints/trace_cntrl_32_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_7/bd_b441_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_8/bd_b441_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_9/bd_b441_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axis_data_fifo_0_3/base_axis_data_fifo_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_1/bd_7480_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_1/bd_7480_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_5/bd_7480_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_6/bd_7480_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_7/bd_7480_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_8/bd_7480_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/bd_0/ip/ip_9/bd_7480_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_1/base_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_1/base_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_vdma_0_1/base_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_1/base_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_2/base_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_us_0/base_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_us_0/base_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_us_0/base_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_3/base_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_92/base_s00_regslice_92_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_92/base_s00_regslice_92_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_92/base_m00_regslice_92_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_92/base_m00_regslice_92_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_92/base_m01_regslice_92_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_92/base_m01_regslice_92_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_92/base_m02_regslice_92_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_92/base_m02_regslice_92_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_92/base_m03_regslice_92_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_92/base_m03_regslice_92_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_77/base_m04_regslice_77_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_77/base_m04_regslice_77_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_77/base_m05_regslice_77_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_77/base_m05_regslice_77_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_77/base_m06_regslice_77_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_77/base_m06_regslice_77_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_77/base_m07_regslice_77_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_77/base_m07_regslice_77_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_93/base_s00_regslice_93_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_93/base_s00_regslice_93_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_93/base_m00_regslice_93_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_93/base_m00_regslice_93_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_93/base_m01_regslice_93_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_93/base_m01_regslice_93_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_93/base_m02_regslice_93_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_93/base_m02_regslice_93_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_93/base_m03_regslice_93_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_93/base_m03_regslice_93_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_78/base_m04_regslice_78_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_78/base_m04_regslice_78_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_78/base_m05_regslice_78_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_78/base_m05_regslice_78_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_78/base_m06_regslice_78_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_78/base_m06_regslice_78_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_78/base_m07_regslice_78_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_78/base_m07_regslice_78_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_94/base_s00_regslice_94_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_94/base_s00_regslice_94_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_94/base_m00_regslice_94_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_94/base_m00_regslice_94_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_94/base_m01_regslice_94_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_94/base_m01_regslice_94_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_94/base_m02_regslice_94_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_94/base_m02_regslice_94_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_94/base_m03_regslice_94_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_94/base_m03_regslice_94_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_79/base_m04_regslice_79_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_79/base_m04_regslice_79_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_79/base_m05_regslice_79_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_79/base_m05_regslice_79_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_79/base_m06_regslice_79_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_79/base_m06_regslice_79_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_79/base_m07_regslice_79_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_79/base_m07_regslice_79_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m08_regslice_46/base_m08_regslice_46_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m08_regslice_46/base_m08_regslice_46_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m09_regslice_46/base_m09_regslice_46_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m09_regslice_46/base_m09_regslice_46_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m10_regslice_0/base_m10_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m10_regslice_0/base_m10_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m11_regslice_0/base_m11_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m11_regslice_0/base_m11_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_90/base_s00_regslice_90_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_90/base_s00_regslice_90_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_12/base_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_90/base_m00_regslice_90_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_90/base_m00_regslice_90_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_4/base_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_90/base_m01_regslice_90_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_90/base_m01_regslice_90_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_90/base_m02_regslice_90_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_90/base_m02_regslice_90_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_5/base_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_90/base_m03_regslice_90_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_90/base_m03_regslice_90_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_76/base_m04_regslice_76_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m04_regslice_76/base_m04_regslice_76_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_6/base_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_76/base_m05_regslice_76_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m05_regslice_76/base_m05_regslice_76_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_7/base_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_76/base_m06_regslice_76_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m06_regslice_76/base_m06_regslice_76_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_76/base_m07_regslice_76_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m07_regslice_76/base_m07_regslice_76_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_8/base_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m08_regslice_45/base_m08_regslice_45_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m08_regslice_45/base_m08_regslice_45_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m09_regslice_45/base_m09_regslice_45_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m09_regslice_45/base_m09_regslice_45_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_9/base_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_10/base_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_11/base_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_91/base_s00_regslice_91_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_91/base_s00_regslice_91_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_91/base_m00_regslice_91_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_91/base_m00_regslice_91_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_91/base_m01_regslice_91_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m01_regslice_91/base_m01_regslice_91_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_91/base_m02_regslice_91_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m02_regslice_91/base_m02_regslice_91_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_91/base_m03_regslice_91_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m03_regslice_91/base_m03_regslice_91_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_13/base_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/base_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_1/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_2/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_mb_3/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/constrs_1/imports/constraints/base.xdc
set_property used_in_implementation false [get_files C:/Users/cl/Desktop/OV7670_PYNQ/boards/Pynq-Z2/base/base/base.srcs/constrs_1/imports/constraints/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top base_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef base_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file base_wrapper_utilization_synth.rpt -pb base_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
