# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_address_remap_0_0/base_address_remap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_address_remap_0_0 || ORIG_REF_NAME==base_address_remap_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_0/base_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_0 || ORIG_REF_NAME==base_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_1/base_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_1 || ORIG_REF_NAME==base_xbar_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_mem_intercon_0/base_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_0 || ORIG_REF_NAME==base_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_protocol_convert_0_0/base_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_protocol_convert_0_0 || ORIG_REF_NAME==base_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_btns_gpio_0 || ORIG_REF_NAME==base_btns_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_10MHz_0 || ORIG_REF_NAME==base_clk_wiz_10MHz_0} -quiet] -quiet

# IP: bd/base/ip/base_concat_interrupts_0/base_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_concat_interrupts_0 || ORIG_REF_NAME==base_concat_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_concat_pmodb_0/base_concat_pmodb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_concat_pmodb_0 || ORIG_REF_NAME==base_concat_pmodb_0} -quiet] -quiet

# IP: bd/base/ip/base_concat_rp_0/base_concat_rp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_concat_rp_0 || ORIG_REF_NAME==base_concat_rp_0} -quiet] -quiet

# IP: bd/base/ip/base_constant_8bit_0_0/base_constant_8bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_constant_8bit_0_0 || ORIG_REF_NAME==base_constant_8bit_0_0} -quiet] -quiet

# IP: bd/base/ip/base_iop_interrupts_0/base_iop_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_iop_interrupts_0 || ORIG_REF_NAME==base_iop_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_dff_en_reset_vector_0_1/base_dff_en_reset_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dff_en_reset_vector_0_1 || ORIG_REF_NAME==base_dff_en_reset_vector_0_1} -quiet] -quiet

# IP: bd/base/ip/base_gpio_0/base_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gpio_0 || ORIG_REF_NAME==base_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_iic_0/base_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_iic_0 || ORIG_REF_NAME==base_iic_0} -quiet] -quiet

# IP: bd/base/ip/base_intc_1/base_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intc_1 || ORIG_REF_NAME==base_intc_1} -quiet] -quiet

# IP: bd/base/ip/base_intr_1/base_intr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_1 || ORIG_REF_NAME==base_intr_1} -quiet] -quiet

# IP: bd/base/ip/base_intr_concat_0/base_intr_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_concat_0 || ORIG_REF_NAME==base_intr_concat_0} -quiet] -quiet

# IP: bd/base/ip/base_io_switch_1/base_io_switch_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_io_switch_1 || ORIG_REF_NAME==base_io_switch_1} -quiet] -quiet

# IP: bd/base/ip/base_dlmb_v10_1/base_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dlmb_v10_1 || ORIG_REF_NAME==base_dlmb_v10_1} -quiet] -quiet

# IP: bd/base/ip/base_ilmb_v10_1/base_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ilmb_v10_1 || ORIG_REF_NAME==base_ilmb_v10_1} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_1/base_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_1 || ORIG_REF_NAME==base_lmb_bram_1} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_if_cntlr_1/base_lmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_if_cntlr_1 || ORIG_REF_NAME==base_lmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/base/ip/base_logic_1_1/base_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_logic_1_1 || ORIG_REF_NAME==base_logic_1_1} -quiet] -quiet

# IP: bd/base/ip/base_mb_1/base_mb_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_1 || ORIG_REF_NAME==base_mb_1} -quiet] -quiet

# IP: bd/base/ip/base_mb_bram_ctrl_1/base_mb_bram_ctrl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_bram_ctrl_1 || ORIG_REF_NAME==base_mb_bram_ctrl_1} -quiet] -quiet

# IP: bd/base/ip/base_xbar_3/base_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_3 || ORIG_REF_NAME==base_xbar_3} -quiet] -quiet

# IP: bd/base/ip/base_microblaze_0_axi_periph_1/base_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_microblaze_0_axi_periph_1 || ORIG_REF_NAME==base_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/base/ip/base_rst_clk_wiz_1_100M_1/base_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==base_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/base/ip/base_spi_0/base_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_spi_0 || ORIG_REF_NAME==base_spi_0} -quiet] -quiet

# IP: bd/base/ip/base_timer_6/base_timer_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_timer_6 || ORIG_REF_NAME==base_timer_6} -quiet] -quiet

# IP: bd/base/ip/base_dff_en_reset_vector_0_2/base_dff_en_reset_vector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dff_en_reset_vector_0_2 || ORIG_REF_NAME==base_dff_en_reset_vector_0_2} -quiet] -quiet

# IP: bd/base/ip/base_gpio_1/base_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_gpio_1 || ORIG_REF_NAME==base_gpio_1} -quiet] -quiet

# IP: bd/base/ip/base_iic_1/base_iic_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_iic_1 || ORIG_REF_NAME==base_iic_1} -quiet] -quiet

# IP: bd/base/ip/base_intc_2/base_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intc_2 || ORIG_REF_NAME==base_intc_2} -quiet] -quiet

# IP: bd/base/ip/base_intr_2/base_intr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_2 || ORIG_REF_NAME==base_intr_2} -quiet] -quiet

# IP: bd/base/ip/base_intr_concat_1/base_intr_concat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_concat_1 || ORIG_REF_NAME==base_intr_concat_1} -quiet] -quiet

# IP: bd/base/ip/base_io_switch_2/base_io_switch_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_io_switch_2 || ORIG_REF_NAME==base_io_switch_2} -quiet] -quiet

# IP: bd/base/ip/base_dlmb_v10_2/base_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dlmb_v10_2 || ORIG_REF_NAME==base_dlmb_v10_2} -quiet] -quiet

# IP: bd/base/ip/base_ilmb_v10_2/base_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ilmb_v10_2 || ORIG_REF_NAME==base_ilmb_v10_2} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_2/base_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_2 || ORIG_REF_NAME==base_lmb_bram_2} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_if_cntlr_2/base_lmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_if_cntlr_2 || ORIG_REF_NAME==base_lmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/base/ip/base_logic_1_2/base_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_logic_1_2 || ORIG_REF_NAME==base_logic_1_2} -quiet] -quiet

# IP: bd/base/ip/base_mb_2/base_mb_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_2 || ORIG_REF_NAME==base_mb_2} -quiet] -quiet

# IP: bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_bram_ctrl_2 || ORIG_REF_NAME==base_mb_bram_ctrl_2} -quiet] -quiet

# IP: bd/base/ip/base_xbar_4/base_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_4 || ORIG_REF_NAME==base_xbar_4} -quiet] -quiet

# IP: bd/base/ip/base_microblaze_0_axi_periph_2/base_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_microblaze_0_axi_periph_2 || ORIG_REF_NAME==base_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/base/ip/base_rst_clk_wiz_1_100M_2/base_rst_clk_wiz_1_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==base_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/base/ip/base_spi_1/base_spi_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_spi_1 || ORIG_REF_NAME==base_spi_1} -quiet] -quiet

# IP: bd/base/ip/base_timer_7/base_timer_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_timer_7 || ORIG_REF_NAME==base_timer_7} -quiet] -quiet

# IP: bd/base/ip/base_dff_en_reset_vector_0_3/base_dff_en_reset_vector_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dff_en_reset_vector_0_3 || ORIG_REF_NAME==base_dff_en_reset_vector_0_3} -quiet] -quiet

# IP: bd/base/ip/base_iic_0_0/base_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_iic_0_0 || ORIG_REF_NAME==base_iic_0_0} -quiet] -quiet

# IP: bd/base/ip/base_iic_1_0/base_iic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_iic_1_0 || ORIG_REF_NAME==base_iic_1_0} -quiet] -quiet

# IP: bd/base/ip/base_intc_3/base_intc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intc_3 || ORIG_REF_NAME==base_intc_3} -quiet] -quiet

# IP: bd/base/ip/base_intr_3/base_intr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_3 || ORIG_REF_NAME==base_intr_3} -quiet] -quiet

# IP: bd/base/ip/base_intr_concat_2/base_intr_concat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_intr_concat_2 || ORIG_REF_NAME==base_intr_concat_2} -quiet] -quiet

# IP: bd/base/ip/base_io_switch_3/base_io_switch_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_io_switch_3 || ORIG_REF_NAME==base_io_switch_3} -quiet] -quiet

# IP: bd/base/ip/base_dlmb_v10_3/base_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dlmb_v10_3 || ORIG_REF_NAME==base_dlmb_v10_3} -quiet] -quiet

# IP: bd/base/ip/base_ilmb_v10_3/base_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ilmb_v10_3 || ORIG_REF_NAME==base_ilmb_v10_3} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_3/base_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_3 || ORIG_REF_NAME==base_lmb_bram_3} -quiet] -quiet

# IP: bd/base/ip/base_lmb_bram_if_cntlr_3/base_lmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_lmb_bram_if_cntlr_3 || ORIG_REF_NAME==base_lmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/base/ip/base_logic_1_3/base_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_logic_1_3 || ORIG_REF_NAME==base_logic_1_3} -quiet] -quiet

# IP: bd/base/ip/base_mb_3/base_mb_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_3 || ORIG_REF_NAME==base_mb_3} -quiet] -quiet

# IP: bd/base/ip/base_mb_bram_ctrl_3/base_mb_bram_ctrl_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_bram_ctrl_3 || ORIG_REF_NAME==base_mb_bram_ctrl_3} -quiet] -quiet

# IP: bd/base/ip/base_xbar_5/base_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_5 || ORIG_REF_NAME==base_xbar_5} -quiet] -quiet

# IP: bd/base/ip/base_microblaze_0_axi_periph_3/base_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_microblaze_0_axi_periph_3 || ORIG_REF_NAME==base_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/base/ip/base_rpi_gpio_0/base_rpi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_gpio_0 || ORIG_REF_NAME==base_rpi_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_clk_wiz_1_100M_3/base_rst_clk_wiz_1_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==base_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/base/ip/base_spi_0_0/base_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_spi_0_0 || ORIG_REF_NAME==base_spi_0_0} -quiet] -quiet

# IP: bd/base/ip/base_spi_1_0/base_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_spi_1_0 || ORIG_REF_NAME==base_spi_1_0} -quiet] -quiet

# IP: bd/base/ip/base_mb4_timer_pwm_0/base_mb4_timer_pwm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb4_timer_pwm_0 || ORIG_REF_NAME==base_mb4_timer_pwm_0} -quiet] -quiet

# IP: bd/base/ip/base_mb4_timers_interrupt_0/base_mb4_timers_interrupt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb4_timers_interrupt_0 || ORIG_REF_NAME==base_mb4_timers_interrupt_0} -quiet] -quiet

# IP: bd/base/ip/base_timer_0_1/base_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_timer_0_1 || ORIG_REF_NAME==base_timer_0_1} -quiet] -quiet

# IP: bd/base/ip/base_timer_1_1/base_timer_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_timer_1_1 || ORIG_REF_NAME==base_timer_1_1} -quiet] -quiet

# IP: bd/base/ip/base_uartlite_1/base_uartlite_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_uartlite_1 || ORIG_REF_NAME==base_uartlite_1} -quiet] -quiet

# IP: bd/base/ip/base_leds_gpio_0/base_leds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_leds_gpio_0 || ORIG_REF_NAME==base_leds_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_logic_1_4/base_logic_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_logic_1_4 || ORIG_REF_NAME==base_logic_1_4} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_arduino_intr_ack_0/base_mb_iop_arduino_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_arduino_intr_ack_0 || ORIG_REF_NAME==base_mb_iop_arduino_intr_ack_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_arduino_reset_0/base_mb_iop_arduino_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_arduino_reset_0 || ORIG_REF_NAME==base_mb_iop_arduino_reset_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_pmoda_intr_ack_0/base_mb_iop_pmoda_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_pmoda_intr_ack_0 || ORIG_REF_NAME==base_mb_iop_pmoda_intr_ack_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_pmoda_reset_0/base_mb_iop_pmoda_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_pmoda_reset_0 || ORIG_REF_NAME==base_mb_iop_pmoda_reset_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_pmodb_intr_ack_0/base_mb_iop_pmodb_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_pmodb_intr_ack_0 || ORIG_REF_NAME==base_mb_iop_pmodb_intr_ack_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_pmodb_reset_0/base_mb_iop_pmodb_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_pmodb_reset_0 || ORIG_REF_NAME==base_mb_iop_pmodb_reset_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_rpi_intr_ack_0/base_mb_iop_rpi_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_rpi_intr_ack_0 || ORIG_REF_NAME==base_mb_iop_rpi_intr_ack_0} -quiet] -quiet

# IP: bd/base/ip/base_mb_iop_rpi_reset_0/base_mb_iop_rpi_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_iop_rpi_reset_0 || ORIG_REF_NAME==base_mb_iop_rpi_reset_0} -quiet] -quiet

# IP: bd/base/ip/base_mdm_1_0/base_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mdm_1_0 || ORIG_REF_NAME==base_mdm_1_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rp_pin_sel_0/base_pmoda_rp_pin_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rp_pin_sel_0 || ORIG_REF_NAME==base_pmoda_rp_pin_sel_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_6/base_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_6 || ORIG_REF_NAME==base_xbar_6} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_7/base_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_7 || ORIG_REF_NAME==base_xbar_7} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph1_0/base_ps7_0_axi_periph1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph1_0 || ORIG_REF_NAME==base_ps7_0_axi_periph1_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_8/base_xbar_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_8 || ORIG_REF_NAME==base_xbar_8} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_1_0/base_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rgbleds_gpio_0 || ORIG_REF_NAME==base_rgbleds_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk3_0/base_rst_ps7_0_fclk3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk3_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk3_0} -quiet] -quiet

# IP: bd/base/ip/base_slice_pmodb_gpio_0/base_slice_pmodb_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_slice_pmodb_gpio_0 || ORIG_REF_NAME==base_slice_pmodb_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_switches_gpio_0/base_switches_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_switches_gpio_0 || ORIG_REF_NAME==base_switches_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_interrupts_0 || ORIG_REF_NAME==base_system_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_0_0/base_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_0_0 || ORIG_REF_NAME==base_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/base/ip/base_constant_tkeep_tstrb_0/base_constant_tkeep_tstrb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_constant_tkeep_tstrb_0 || ORIG_REF_NAME==base_constant_tkeep_tstrb_0} -quiet] -quiet

# IP: bd/base/ip/base_trace_cntrl_64_0_0/base_trace_cntrl_64_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_trace_cntrl_64_0_0 || ORIG_REF_NAME==base_trace_cntrl_64_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_dma_0_1/base_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_0_1 || ORIG_REF_NAME==base_axi_dma_0_1} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_0_1/base_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_0_1 || ORIG_REF_NAME==base_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/base/ip/base_constant_tkeep_tstrb_1/base_constant_tkeep_tstrb_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_constant_tkeep_tstrb_1 || ORIG_REF_NAME==base_constant_tkeep_tstrb_1} -quiet] -quiet

# IP: bd/base/ip/base_trace_cntrl_32_0_0/base_trace_cntrl_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_trace_cntrl_32_0_0 || ORIG_REF_NAME==base_trace_cntrl_32_0_0} -quiet] -quiet

# IP: bd/base/ip/base_collector_pmoda_rpi_0/base_collector_pmoda_rpi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_collector_pmoda_rpi_0 || ORIG_REF_NAME==base_collector_pmoda_rpi_0} -quiet] -quiet

# IP: bd/base/ip/base_collector_rpi_27_8_0/base_collector_rpi_27_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_collector_rpi_27_8_0 || ORIG_REF_NAME==base_collector_rpi_27_8_0} -quiet] -quiet

# IP: bd/base/ip/base_distributor_pmoda_0/base_distributor_pmoda_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_distributor_pmoda_0 || ORIG_REF_NAME==base_distributor_pmoda_0} -quiet] -quiet

# IP: bd/base/ip/base_distributor_rpi_0/base_distributor_rpi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_distributor_rpi_0 || ORIG_REF_NAME==base_distributor_rpi_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_o_sel_0/base_pmoda_rpi_o_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_o_sel_0 || ORIG_REF_NAME==base_pmoda_rpi_o_sel_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_t_sel_0/base_pmoda_rpi_t_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_t_sel_0 || ORIG_REF_NAME==base_pmoda_rpi_t_sel_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_i_27_0_0/base_rpi_i_27_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_i_27_0_0 || ORIG_REF_NAME==base_rpi_i_27_0_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_1_0_0/base_pmoda_rpi_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_1_0_0 || ORIG_REF_NAME==base_pmoda_rpi_1_0_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_3_2_0/base_pmoda_rpi_3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_3_2_0 || ORIG_REF_NAME==base_pmoda_rpi_3_2_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_5_4_0/base_pmoda_rpi_5_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_5_4_0 || ORIG_REF_NAME==base_pmoda_rpi_5_4_0} -quiet] -quiet

# IP: bd/base/ip/base_pmoda_rpi_7_6_0/base_pmoda_rpi_7_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pmoda_rpi_7_6_0 || ORIG_REF_NAME==base_pmoda_rpi_7_6_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi2pmoda_0/base_rpi2pmoda_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi2pmoda_0 || ORIG_REF_NAME==base_rpi2pmoda_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_o_27_8_0/base_rpi_o_27_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_o_27_8_0 || ORIG_REF_NAME==base_rpi_o_27_8_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi2pmoda_1/base_rpi2pmoda_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi2pmoda_1 || ORIG_REF_NAME==base_rpi2pmoda_1} -quiet] -quiet

# IP: bd/base/ip/base_rpi_1_0_0/base_rpi_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_1_0_0 || ORIG_REF_NAME==base_rpi_1_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_3_2_0/base_rpi_3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_3_2_0 || ORIG_REF_NAME==base_rpi_3_2_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_5_4_0/base_rpi_5_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_5_4_0 || ORIG_REF_NAME==base_rpi_5_4_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_7_6_0/base_rpi_7_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_7_6_0 || ORIG_REF_NAME==base_rpi_7_6_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi_t_27_8_0/base_rpi_t_27_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_t_27_8_0 || ORIG_REF_NAME==base_rpi_t_27_8_0} -quiet] -quiet

# IP: bd/base/ip/base_rpi2pmoda_2/base_rpi2pmoda_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi2pmoda_2 || ORIG_REF_NAME==base_rpi2pmoda_2} -quiet] -quiet

# IP: bd/base/ip/base_rpi_1_0_1/base_rpi_1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_1_0_1 || ORIG_REF_NAME==base_rpi_1_0_1} -quiet] -quiet

# IP: bd/base/ip/base_rpi_3_2_1/base_rpi_3_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_3_2_1 || ORIG_REF_NAME==base_rpi_3_2_1} -quiet] -quiet

# IP: bd/base/ip/base_rpi_5_4_1/base_rpi_5_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_5_4_1 || ORIG_REF_NAME==base_rpi_5_4_1} -quiet] -quiet

# IP: bd/base/ip/base_rpi_7_6_1/base_rpi_7_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rpi_7_6_1 || ORIG_REF_NAME==base_rpi_7_6_1} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_1/base_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_1 || ORIG_REF_NAME==base_xlconcat_0_1} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_0_0/base_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_0_0 || ORIG_REF_NAME==base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_0/base_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_0 || ORIG_REF_NAME==base_smartconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_0_3/base_axis_data_fifo_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_0_3 || ORIG_REF_NAME==base_axis_data_fifo_0_3} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_1/base_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_1 || ORIG_REF_NAME==base_smartconnect_0_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_1/base_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_1 || ORIG_REF_NAME==base_axi_vdma_0_1} -quiet] -quiet

# IP: bd/base/ip/base_camera_decode_0_1/base_camera_decode_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_camera_decode_0_1 || ORIG_REF_NAME==base_camera_decode_0_1} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_0_0/base_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlslice_0_0 || ORIG_REF_NAME==base_xlslice_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_0_0/base_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconstant_0_0 || ORIG_REF_NAME==base_xlconstant_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_0_1/base_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconstant_0_1 || ORIG_REF_NAME==base_xlconstant_0_1} -quiet] -quiet

# IP: bd/base/ip/base_notgate_0_0/base_notgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_notgate_0_0 || ORIG_REF_NAME==base_notgate_0_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_2/base_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_2 || ORIG_REF_NAME==base_auto_pc_2} -quiet] -quiet

# IP: bd/base/ip/base_auto_us_0/base_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_3/base_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_3 || ORIG_REF_NAME==base_auto_pc_3} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_92/base_s00_regslice_92.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_92 || ORIG_REF_NAME==base_s00_regslice_92} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_92/base_m00_regslice_92.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_92 || ORIG_REF_NAME==base_m00_regslice_92} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_92/base_m01_regslice_92.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_92 || ORIG_REF_NAME==base_m01_regslice_92} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_92/base_m02_regslice_92.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_92 || ORIG_REF_NAME==base_m02_regslice_92} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_92/base_m03_regslice_92.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_92 || ORIG_REF_NAME==base_m03_regslice_92} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_77/base_m04_regslice_77.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m04_regslice_77 || ORIG_REF_NAME==base_m04_regslice_77} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_77/base_m05_regslice_77.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m05_regslice_77 || ORIG_REF_NAME==base_m05_regslice_77} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_77/base_m06_regslice_77.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m06_regslice_77 || ORIG_REF_NAME==base_m06_regslice_77} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_77/base_m07_regslice_77.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m07_regslice_77 || ORIG_REF_NAME==base_m07_regslice_77} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_93/base_s00_regslice_93.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_93 || ORIG_REF_NAME==base_s00_regslice_93} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_93/base_m00_regslice_93.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_93 || ORIG_REF_NAME==base_m00_regslice_93} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_93/base_m01_regslice_93.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_93 || ORIG_REF_NAME==base_m01_regslice_93} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_93/base_m02_regslice_93.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_93 || ORIG_REF_NAME==base_m02_regslice_93} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_93/base_m03_regslice_93.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_93 || ORIG_REF_NAME==base_m03_regslice_93} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_78/base_m04_regslice_78.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m04_regslice_78 || ORIG_REF_NAME==base_m04_regslice_78} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_78/base_m05_regslice_78.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m05_regslice_78 || ORIG_REF_NAME==base_m05_regslice_78} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_78/base_m06_regslice_78.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m06_regslice_78 || ORIG_REF_NAME==base_m06_regslice_78} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_78/base_m07_regslice_78.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m07_regslice_78 || ORIG_REF_NAME==base_m07_regslice_78} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_94/base_s00_regslice_94.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_94 || ORIG_REF_NAME==base_s00_regslice_94} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_94/base_m00_regslice_94.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_94 || ORIG_REF_NAME==base_m00_regslice_94} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_94/base_m01_regslice_94.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_94 || ORIG_REF_NAME==base_m01_regslice_94} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_94/base_m02_regslice_94.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_94 || ORIG_REF_NAME==base_m02_regslice_94} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_94/base_m03_regslice_94.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_94 || ORIG_REF_NAME==base_m03_regslice_94} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_79/base_m04_regslice_79.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m04_regslice_79 || ORIG_REF_NAME==base_m04_regslice_79} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_79/base_m05_regslice_79.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m05_regslice_79 || ORIG_REF_NAME==base_m05_regslice_79} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_79/base_m06_regslice_79.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m06_regslice_79 || ORIG_REF_NAME==base_m06_regslice_79} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_79/base_m07_regslice_79.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m07_regslice_79 || ORIG_REF_NAME==base_m07_regslice_79} -quiet] -quiet

# IP: bd/base/ip/base_m08_regslice_46/base_m08_regslice_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m08_regslice_46 || ORIG_REF_NAME==base_m08_regslice_46} -quiet] -quiet

# IP: bd/base/ip/base_m09_regslice_46/base_m09_regslice_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m09_regslice_46 || ORIG_REF_NAME==base_m09_regslice_46} -quiet] -quiet

# IP: bd/base/ip/base_m10_regslice_0/base_m10_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m10_regslice_0 || ORIG_REF_NAME==base_m10_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m11_regslice_0/base_m11_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m11_regslice_0 || ORIG_REF_NAME==base_m11_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_90/base_s00_regslice_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_90 || ORIG_REF_NAME==base_s00_regslice_90} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_12/base_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_12 || ORIG_REF_NAME==base_auto_pc_12} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_90/base_m00_regslice_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_90 || ORIG_REF_NAME==base_m00_regslice_90} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_4 || ORIG_REF_NAME==base_auto_pc_4} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_90/base_m01_regslice_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_90 || ORIG_REF_NAME==base_m01_regslice_90} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_90/base_m02_regslice_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_90 || ORIG_REF_NAME==base_m02_regslice_90} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_5/base_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_5 || ORIG_REF_NAME==base_auto_pc_5} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_90/base_m03_regslice_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_90 || ORIG_REF_NAME==base_m03_regslice_90} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_76/base_m04_regslice_76.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m04_regslice_76 || ORIG_REF_NAME==base_m04_regslice_76} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_6/base_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_6 || ORIG_REF_NAME==base_auto_pc_6} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_76/base_m05_regslice_76.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m05_regslice_76 || ORIG_REF_NAME==base_m05_regslice_76} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_7/base_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_7 || ORIG_REF_NAME==base_auto_pc_7} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_76/base_m06_regslice_76.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m06_regslice_76 || ORIG_REF_NAME==base_m06_regslice_76} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_76/base_m07_regslice_76.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m07_regslice_76 || ORIG_REF_NAME==base_m07_regslice_76} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_8/base_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_8 || ORIG_REF_NAME==base_auto_pc_8} -quiet] -quiet

# IP: bd/base/ip/base_m08_regslice_45/base_m08_regslice_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m08_regslice_45 || ORIG_REF_NAME==base_m08_regslice_45} -quiet] -quiet

# IP: bd/base/ip/base_m09_regslice_45/base_m09_regslice_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m09_regslice_45 || ORIG_REF_NAME==base_m09_regslice_45} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_9/base_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_9 || ORIG_REF_NAME==base_auto_pc_9} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_10/base_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_10 || ORIG_REF_NAME==base_auto_pc_10} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_11/base_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_11 || ORIG_REF_NAME==base_auto_pc_11} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_91/base_s00_regslice_91.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_91 || ORIG_REF_NAME==base_s00_regslice_91} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_91/base_m00_regslice_91.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_91 || ORIG_REF_NAME==base_m00_regslice_91} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_91/base_m01_regslice_91.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_91 || ORIG_REF_NAME==base_m01_regslice_91} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_91/base_m02_regslice_91.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_91 || ORIG_REF_NAME==base_m02_regslice_91} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_91/base_m03_regslice_91.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_91 || ORIG_REF_NAME==base_m03_regslice_91} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_13/base_auto_pc_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_13 || ORIG_REF_NAME==base_auto_pc_13} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
